swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  account:
    post:
      security:
        - Bearer: []
      tags: 
        -  User module
      summary: Returns all transactions
      description: API for fetching a user account
      responses: 
        '200':
          description: User's transactions retrieved successfully
        '400':
          description: Invalid Id
        '404':
          description: Accounts not found
        '500':
          description: Internal Server Error
  account/{transaction_id}/{category_id}:
    patch:
      tags: 
        -  User Module
      summary: Updates the category of transaction
      description: API for updating the category of transaction
      parameters:
        - in: body
          name: body
          description: Adding or update a note
          required: true
          schema:
            $ref: '#/definitions/CategoryById'
      responses: 
        '200':
          description: Successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Category not found
        '500':
          description: Internal Server Error
  account/{transaction_id}/note:
    patch:
      tags: 
        -  User Module
      summary: Add or update the note of transaction
      description: API for adding or updating the note of transaction
      parameters:
        - in: body
          name: body
          description: Adding or update a note
          required: true
          schema:
            $ref: '#/definitions/Note'
      responses: 
        '200':
          description: User's operations retrieved successfully
        '400':
          description: Invalid Id
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transaction:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id: 
            type: integer
            format: int64
            example: 2430
          account_title:
            type: string
            example: credit card
          transactionType: 
            schema: 
              $ref: '#/definitions/transactionType'
          date: 
            type: string
            example: '2022-04-29T20:28:45.744Z'
          description:
            type: string
            example: Golden Sun Bakery
          category:
            schema: 
              $ref: '#/definitions/category'
          note: 
            type: string
            xml: note
          amount: 
            type: string
  TransactionType:
    type: object
    properties:
      name:
        type: string
        example: Electronic
    xml: transactionType
  Category:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 1
      name:
        type: string
        example: Food
    xml:
      name: category
